<?php
/**
 * Ofertasmall Ofertas - Custom Admin settings
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  Pablo S G Pacheco
 */

namespace TxToIT\OMO;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'TxToIT\OMO\Custom_Admin_Settings' ) ) {
	class Custom_Admin_Settings extends \WeDevs_Settings_API {

		function set_fields( $fields ) {
			foreach ( $fields as $section => $field ) {
				foreach ( $field as $key => $option ) {
					if ( $option['type'] == 'title' ) {
						$fields[ $section ][ $key ]['class'] = 'wedevs-title';
						$fields[ $section ][ $key ]['name']  = substr( md5( openssl_random_pseudo_bytes( 20 ) ), - 6 );
					}
				}
			}
			$this->settings_fields = $fields;

			return $this;
		}

		/**
		 * Displays a password field for a settings field
		 *
		 * @param array $args settings field args
		 */
		/*function callback_password( $args ) {

			$value = esc_attr( $this->get_option( $args['id'], $args['section'], $args['std'] ) );
			$size  = isset( $args['size'] ) && !is_null( $args['size'] ) ? $args['size'] : 'regular';

			$html  = sprintf( '<input autocomplete="off" type="password" class="%1$s-text" id="%2$s[%3$s]" name="%2$s[%3$s]" value="%4$s"/>', $size, $args['section'], $args['id'], $value );
			$html  .= $this->get_field_description( $args );
			$id = $args['id'];
			echo $html;
		}*/

		/**
		 * Displays a title field
		 *
		 * @version 1.0.0
		 * @since   1.0.0
		 *
		 * @param array $args settings field args
		 */
		function callback_title( $args ) {
			$html = $this->get_field_description( $args );
			echo $html;
		}

		function _style_fix() {
			parent::_style_fix(); // TODO: Change the autogenerated stub
			?>
            <style type="text/css">
                /** For Title setting field **/
                #wpbody-content .metabox-holder h2 {
                    padding: 0 !important;
                }

                .wedevs-title th {
                    color: #23282d;
                }

                .wedevs-title label {
                    font-size: 1.3em !important;
                }

                .wedevs-title * {
                    cursor: auto;
                }
            </style>
			<?php
		}

		/**
		 * Show the section settings forms
		 *
		 * This function displays every sections in a different form
		 */
		function show_forms() {
			?>
            <div class="metabox-holder">
				<?php foreach ( $this->settings_sections as $form ) { ?>
                    <div id="<?php echo $form['id']; ?>" class="group" style="display: none;">
                        <form method="post" action="options.php">
							<?php
							do_action( 'wsa_form_top_' . $form['id'], $form );
							settings_fields( $form['id'] );
							do_settings_sections( $form['id'] );
							do_action( 'wsa_form_bottom_' . $form['id'], $form );
							if ( isset( $this->settings_fields[ $form['id'] ] ) ):
								?>
                                <div style="">
									<?php submit_button(); ?>
                                </div>
							<?php endif; ?>
                        </form>
                    </div>
				<?php } ?>
            </div>
			<?php
			$this->script();
		}
	}
}