<?php
/**
 * Ofertasmall Ofertas - Import Background Process
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  Pablo S G Pacheco
 */

namespace TxToIT\OMO;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'TxToIT\OMO\Import_Background_Process' ) ) {
	class Import_Background_Process extends \WP_Background_Process {
		/**
		 * @var string
		 */
		protected $action = '_omo_offer_import_process';
		public static $current_parent_id = '';

		protected function task( $item ) {


			//error_log( '-----bkg-process-----' );
			//error_log( print_r( $item, true ) );
			//error_log( print_r( $store, true ) );

			//if ( ! empty( $store ) ) {
				/*$count = get_option( '_omo_import_count', 0 );
				$count ++;
				update_option( '_omo_import_count', $count, false );*/

				$import = new Import( array(
					'offers_post_type' => Offer_CPT::$post_type,
					'offer_tax'       => Store_Tax::$taxonomy
				) );
				return $import->update_bkg_process_task($item);

				/*reset( $store );
				$first_key = key( $store );
				$import->import_offer( $store[ $first_key ] );

				return false;*/
			//}
		}

		protected function complete() {
			parent::complete(); // TODO: Change the autogenerated stub
			//update_option( '_omo_import_count', 0, false );
			//delete_option( '_omo_offers_from_api' );
			//delete_option()
		}
	}
}